language: generic

services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose up -d

after_success:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u webdesignpastor --password-stdin

  - docker-compose push back
  - docker-compose push front

jobs:
  include:
    - stage: Deploy
      script:
        - ssh -o StrictHostKeyChecking=no ubuntu@your_aws_instance_ip "git pull && docker-compose pull && docker-compose up -d"
