language: generic

services:
  - docker

before_install:
  - echo -e $ENCODED_SSH_KEY > TimeManagerKey.pem
  - chmod 600 TimeManagerKey.pem
  - docker-compose build

script:
  - docker-compose up -d

after_success:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u webdesignpastor --password-stdin
  - docker-compose push back
  - docker-compose push front

jobs:
  include:
    - stage: Deploy
      script:
        - ssh -o StrictHostKeyChecking=no -i TimeManagerKey.pem ec2-user@16.16.25.106 "git pull && docker-compose pull && docker-compose up -d"
